CREATE TABLE TODO(ID INT NOT NULL AUTO_INCREMENT, NAME VARCHAR(50) , PRIMARY KEY(ID));
CREATE TABLE ACCOUNT(ID INT NOT NULL AUTO_INCREMENT, BALANCE INT, TYPE VARCHAR(50), PRIMARY KEY(ID));
CREATE TABLE TRANSFER(ID INT NOT NULL AUTO_INCREMENT, FROM_ACCOUNT_ID INT, TO_ACCOUNT_ID INT, AMOUNT INT,
 STATUS VARCHAR(50), TRANSFER_INITIATED_TIMESTAMP TIMESTAMP, PRIMARY KEY(ID),
  FOREIGN KEY (FROM_ACCOUNT_ID) REFERENCES ACCOUNT(ID), FOREIGN KEY (TO_ACCOUNT_ID) REFERENCES ACCOUNT(ID));
COMMIT;